### ISSUE TITLE
Keyboard layout missing enter 1.10

### ISSUE THREAD

**Issue by LuSo58** [TravFitz/Firefox-On-Screen-Keyboard#5]
Version 1.10 has an issue with missing Enter, which breaks the layout and makes it unusable for touch only devices. 1.9 works fine
![Screenshot from 2021-03-20 17-01-58](https://user-images.githubusercontent.com/22314804/111876373-b3d74600-899e-11eb-8dcb-84401917e040.png)

**Comment by TravFitz** [comment]
Hi @LuSo58, the Enter key doesn't actually do anything (it didn't do anything in 1.9 either). The biggest issue with it is that a lot of websites these days require you to select the "submit" button for their javascript to run on, and on top of that most of those websites also listen for synthesized input as well, so you cannot fake a keystroke or click. I did some testing on the enter button submitting forms, it does indeed work for some websites but a large majority of the ones that I tested it failed on, it didn't give a reason why it just took you to an error page. 

With these in mind I decided it was worth not having the Enter key until it can be fully functional otherwise it can cause more issues than it solves. I am however still looking into a way to make it fully functional.

If you can think of a key that would be useful to have full time in replacement of the Enter key I am more than happy to instate that to fix the layout.
